# Created By Prabin K Datta
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'CountrySearch' do
    use_frameworks!
    pod 'AFNetworking', '~> 3.0'
    pod 'SwiftyJSON'
end
